### ISSUE TITLE
Basti init asks for a connection target 

### ISSUE THREAD

**Issue by RomanHotsiy** [BohdanPetryshyn/basti#13]
I'm not sure why basti init asks for a connection target but then basti connect asks it again.

If there are some steps needed to init the connection this should support multi-select.

**Comment by BohdanPetryshyn** [comment]
`basti init` needs the connection target to set up all the underlying infrastructure to work specifically with the given target. Then, `basti connect` asks you for the connection target again so that you can select what target you want to connect to. The point is that you can have multiple targets in your account. 

To set up multiple targets, you have to call `basti init` multiple times. Basti will reuse part of the existing infrastructure if possible.

**Comment by BohdanPetryshyn** [comment]
To avoid selecting all the connection parameters each time, we can introduce some state to Basti that would be kept on the user's machine.

**Comment by BohdanPetryshyn** [comment]
Could you please elaborate a little bit more on the second part?

> If there are some steps needed to init the connection this should support multi-select.

**Comment by RomanHotsiy** [comment]
> If there are some steps needed to init the connection this should support multi-select.

Yes, I should be able to select multiple targets using multi-select:

![image](https://user-images.githubusercontent.com/3975738/205447587-8ca8dc05-67ec-476b-9403-741034100e5a.png)

**Comment by BohdanPetryshyn** [comment]
Closing this issue in favor of:

1. #14 for reusing previous inputs with a local state
2. #40 for support for multiple simultaneous connections
